version: '3.1'

services:
  db_1:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'digitro123'

  express:
    build: ./api-agents-registration
    entrypoint: ["sh", "/home/node/express/.docker/entrypoint.sh"]
    container_name: api-nodejs-express
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      DB_MONGO_USER: 'root'
      DB_MONGO_PASSWORD: 'digitro123'
      DB_MONGO_HOST: 'mongo_db'
      DB_MONGO_NAME: 'digitro'
      DB_MONGO_PORT: 27017
      SERVER_PORT: 3000
      SECRET_KEY: 'u9m(}5`6:[M`IIV/8%86s<yWCXA*aHOP4g:0Hv{vqs,;G1{@!0TC:#!7mu54_8x'

    expose:
      - 3000
    ports:
      - 3000:3000

    volumes:
      - ./api-agents-registration:/home/node/express
    depends_on:
      - db_1